In [6]:
import numpy as np
import pandas as pd
import seaborn as sns

In [7]:
df=sns.load_dataset('tips')

In [8]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [9]:
# chi square test > through two ways

In [10]:
df[['sex','smoker']]

sex smoker
0    Female     No
1      Male     No
2      Male     No
3      Male     No
4    Female     No
..      ...    ...
239    Male     No
240  Female    Yes
241    Male    Yes
242    Male     No
243  Female     No

[244 rows x 2 columns]

In [11]:
data_table=pd.crosstab(df['sex'],df['smoker'])

In [12]:
data_table

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [13]:
#observed value and expected value

In [14]:
observed_values=data_table.values


In [15]:
observed_values

array([[60, 97],
       [33, 54]], dtype=int64)

In [16]:
#1st approach>>allowing chi2 itself some expected values

In [17]:
from scipy import stats
stats.chi2_contingency(observed_values)

Chi2ContingencyResult(statistic=0.0, pvalue=1.0, dof=1, expected_freq=array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]]))

In [18]:
stats_test,p,dof,expected_values=stats.chi2_contingency(observed_values)

In [19]:
expected_values

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [20]:
p

1.0

In [21]:
dof

1

In [22]:
observed_values

array([[60, 97],
       [33, 54]], dtype=int64)

In [23]:
for i in zip(observed_values,expected_values):
    print(i)

(array([60, 97], dtype=int64), array([59.84016393, 97.15983607]))
(array([33, 54], dtype=int64), array([33.15983607, 53.84016393]))


In [24]:
chisquare_test=sum([(o-e)**2/e for o,e in zip(observed_values,expected_values)])

In [25]:
chisquare_test

array([0.00119737, 0.00073745])

In [26]:
chisquare_stats=chisquare_test[0]+chisquare_test[1]

In [27]:
chisquare_stats

0.001934818536627623

In [28]:
dof

1

In [34]:
#another approach
# no of hours studies daily on a weekly basis
# monday,tusday ......... sunday

In [35]:
expected_data=[8,5,6,8,5,7,6]
observed_data=[7,4,7,9,4,8,6]

In [36]:
sum(expected_data),sum(observed_data)

(45, 45)

In [38]:
ch_stats,pvalue=stats.chisquare(observed_data,expected_data)

In [39]:
ch_stats,pvalue

(0.9595238095238094, 0.9871002325555286)

In [40]:
# find the critical

In [42]:
dof=len(observed_data)-1

In [43]:
dof

6

NameError: name 'critical_value' is not defined

In [45]:
# Ftest

In [47]:
worker1=[18,17,20,25,27,55,51,42,46,49]
worker2=[18,16,22,26,39,51,48,44,58,12]
np.var(worker1)


202.4

In [49]:
fstats=np.var(worker1)/np.var(worker2)

In [50]:
fstats

0.8246414602346807

In [51]:
df1=len(worker1)-1
df2=len(worker2)-1
alpha=0.05

In [52]:
df1

9

In [53]:
df2

9

In [55]:
import scipy.stats
critical_value=stats.f.ppf(1-alpha,dfn=df1,dfd=df2)

In [56]:
critical_value


3.178893104458269

In [58]:
if fstats>critical_value:
    print("Reject the null hypotheseis")
else:
        print(" fail to reject the null hypotheseis")    

 fail to reject the null hypotheseis


In [59]:
# ANOVA test

In [60]:
# to compare two or more than two means